Приведите пару примеров, когда уместно использовать в коде конструкцию try...catch.

Для того, что бы отловить исключение, используется конструкция try...catch. В блоке try выполняются операции, которые могут привести к исключительной ситуации, а блок catch позволяет принять решение что делать, если исключение было брошено. Эту конструкцию уместно использовать, когда мы подозреваем, что МОЖЕТ БЫТЬ ОШИБКА и чтобы весь сайт не "рухнул" мы добавляем эту конструкцию

****************************
Пример 1

const data = '{"name":"Вася", "age": 30}'; // строка с данными, полученная с сервера

const user = JSON.parse(data); // преобразовали строку в объект

// теперь user -- это JS-объект с данными из строки
alert( user.name ); // Вася
alert( user.age ); // 30

В случае, если данные некорректны, JSON.parse генерирует ошибку, то есть скрипт «упадёт».

Используем try..catch, чтобы обработать некорректный ответ:

const data = "Has Error"; // в данных ошибка

try {

  const user = JSON.parse(data); // <-- ошибка при выполнении
  alert( user.name ); // не сработает

} catch (e) {
  // ...выполнится catch
  alert( "Извините, в данных ошибка, мы попробуем получить их ещё раз" );
  alert( e.name );
  alert( e.message );
}


***********************
Пример 2

Генерация своих ошибок
Предположим, что данные являются корректным JSON… Но в этом объекте нет нужного свойства name:

const data = '{ "age": 30 }'; // данные неполны

try {

  var user = JSON.parse(data); // <-- выполнится без ошибок
  alert( user.name ); // undefined

} catch (e) {
  // не выполнится
  alert( "Извините, в данных ошибка" );
}